### ISSUE TITLE
Provide demo environment in Microsoft Azure

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/containo-deprecated#12]
- [ ] Setup private registry (#9)
- [ ] Setup Kubernetes cluster (#10)
- [ ] Expose APIs via Kong (#11)
- [ ] Update architecture overview
